// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7p25ynbtauzSOuJMoDiYngDnQdndnFco',
    appId: '1:559618081374:web:774520a5e49b5e22cfaacf',
    messagingSenderId: '559618081374',
    projectId: 'satat-b5033',
    authDomain: 'satat-b5033.firebaseapp.com',
    storageBucket: 'satat-b5033.firebasestorage.app',
    measurementId: 'G-ED8EM092MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFqb_Vce_8Elpk0yMKJmZiLjCVS4ApM7E',
    appId: '1:559618081374:android:8a07787f912ef665cfaacf',
    messagingSenderId: '559618081374',
    projectId: 'satat-b5033',
    storageBucket: 'satat-b5033.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHXwk5cP9BDkDykOOjdGlq0D_S1MjvjDU',
    appId: '1:559618081374:ios:6e47f528e9a6f8f9cfaacf',
    messagingSenderId: '559618081374',
    projectId: 'satat-b5033',
    storageBucket: 'satat-b5033.firebasestorage.app',
    iosBundleId: 'com.example.satat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHXwk5cP9BDkDykOOjdGlq0D_S1MjvjDU',
    appId: '1:559618081374:ios:6e47f528e9a6f8f9cfaacf',
    messagingSenderId: '559618081374',
    projectId: 'satat-b5033',
    storageBucket: 'satat-b5033.firebasestorage.app',
    iosBundleId: 'com.example.satat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7p25ynbtauzSOuJMoDiYngDnQdndnFco',
    appId: '1:559618081374:web:db910326ced3bed2cfaacf',
    messagingSenderId: '559618081374',
    projectId: 'satat-b5033',
    authDomain: 'satat-b5033.firebaseapp.com',
    storageBucket: 'satat-b5033.firebasestorage.app',
    measurementId: 'G-2ZH7FGWD6G',
  );
}
